# Generated by Django 3.2.13 on 2022-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
