# Generated by Django 3.2.13 on 2022-04-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PleinAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('advt', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('upload_image', models.FileField(blank=True, upload_to='pleinair/static/pleinair/images')),
            ],
        ),
    ]
