# Generated by Django 3.2.13 on 2022-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleinair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleinair',
            name='upload_image',
            field=models.FileField(blank=True, upload_to='pleinair/images'),
        ),
    ]
