# Generated by Django 3.2.13 on 2022-04-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pleinair', '0002_alter_pleinair_upload_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pleinair',
            old_name='upload_image',
            new_name='image',
        ),
    ]
