version: "3.9"

services:
  web:
    build:
      context: ./belevets
      dockerfile: Dockerfile.prod
    env_file:
      - prod.env
    command: >
      sh -c "python manage.py wait_for_db &&
        python manage.py migrate &&
        gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    expose:
       - 8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data: