# Generated by Django 3.2.13 on 2022-05-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220525_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='extra_image',
            field=models.FileField(blank=True, upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(upload_to='blog/images'),
        ),
    ]
