# Generated by Django 3.2.13 on 2022-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
        ('pleinair', '0003_rename_upload_image_pleinair_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comments',
            field=models.ManyToManyField(default=None, to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(default=None, to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plein_air',
            field=models.ManyToManyField(default=None, to='pleinair.PleinAir'),
        ),
    ]
