# Generated by Django 3.2.13 on 2022-05-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleinair', '0003_rename_upload_image_pleinair_image'),
        ('blog', '0002_comment'),
        ('users', '0002_auto_20220503_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comments',
            field=models.ManyToManyField(to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plein_air',
            field=models.ManyToManyField(to='pleinair.PleinAir'),
        ),
    ]
