# Generated by Django 3.2.13 on 2022-05-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220505_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='plein_air',
            new_name='pleinair',
        ),
    ]
