# Generated by Django 3.2.13 on 2022-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lesson_number'),
        ('users', '0005_auto_20220511_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='order',
            field=models.ManyToManyField(related_name='user_order', to='course.Course'),
        ),
    ]
