# Generated by Django 3.2.13 on 2022-05-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lesson_number'),
        ('users', '0006_userprofile_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment',
            field=models.ManyToManyField(related_name='course_paid', to='course.Course'),
        ),
    ]
