# Generated by Django 3.2.13 on 2022-05-22 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lesson_number'),
        ('users', '0008_remove_userprofile_pleinair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='order',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='course.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
