# Generated by Django 3.2.13 on 2022-05-24 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
